# Generated by Django 2.2.1 on 2019-05-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=200, verbose_name='Composição Atmosferica')),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='fotos/')),
                ('nome', models.CharField(max_length=120)),
                ('rotacao', models.TimeField()),
                ('Translacao', models.PositiveIntegerField()),
                ('Luas', models.PositiveIntegerField()),
                ('fk_composicao', models.ManyToManyField(to='planeta.Composicao')),
                ('fk_posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeta.Posicao')),
            ],
        ),
    ]
